the_eventor/urls.py
from django.contrib import admin
from django.urls import path
from appeventor import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="index"),
    path('about/',views.about,name="about"),
    path('rent-venue/',views.rent_venue,name="rent-venue"),
    path('shows-events/',views.shows_events,name="shows-events"),
    path('corporate_party/',views.corporate_party,name="corporate_party"),
    path('tickets/',views.tickets,name="tickets"),
    path('ticket-details/',views.ticket_details,name="ticket-details"),
    path('event-details/',views.event_details,name="event-details"),
    path('login_user/',views.user_login,name="login_user"),
    path('register/',views.user_register,name="register"),
    path('logout/',views.user_logout,name="logout"),
    path('payment/', views.fake_payment_view, name='payment_page'),
    path('payment_success/<str:transaction_id>', views.payment_success, name='payment_success'),
    path('feedback/', views.feedback_view, name='feedback'),
    path('feedback/success/', views.feedback_success, name='feedback_success'),
    #Admin urls 
    path("adminhome/",views.adminhome,name="adminhome"),
    path("subscription/",views.subscription,name="subscription"),
    path("client-profile/",views.client_profile,name="client-profile"),
    path("send-suggestions/",views.send_suggestions,name="send-suggestions"),
    path("users-profile/",views.admin_profile,name="users-profile"),
    path("view-documents/",views.view_documents,name="view-documents"),
    path("view-receive-payment/",views.view_receive_payment,name="view-receive-payment"),
    path('admin/reservations/', views.show_reservations, name='show_reservations'),
    path("view-suggestions/",views.view_suggestions,name="view-suggestions"),
    path("user_edit/<int:id>",views.user_edit,name="user_edit"),
    path("pages_login/",views.pages_login,name="pages_login"),
    path("admin_logout/",views.admin_log_out,name="admin_logout"),
    path("get-notifications",views.get_notification_count,name="get-notifications"),
    path("delete/<int:id>",views.delete,name="delete"),
    path("update/<int:id>",views.update,name="update"),
    
    #client urls
    path("clienthome/",views.clienthome,name="clienthome"),
    path("payment_info/",views.payment_info,name="payment_info"),
    path("profile/",views.profile,name="profile"),
    path("document/",views.document,name="document"),
    path("delete_data/",views.deletedata,name="delete_data"),
    path("send_query/",views.send_query,name="send_query"),
    path("view_suggestion/",views.view_suggestion,name="view_suggestion"),
   path('upload/', views.document, name="upload_document"),
   path('send_inquiry/', views.send_email, name="send_inquiry"),
    # path("update/<int:id>",views.update,name="update"),
    # path("delete/<int:id>",views.datadelete,name="delete"),
    #  path("datashow/",views.datashow,name="datashow"),
]

appeventor/models.py
from django.db import models
# from django.contrib.auth.models import User 
# Create your models here.
class datadesire(models.Model):
    name=models.CharField(max_length=20)
    email=models.EmailField()
    password=models.CharField(max_length=16)
    
class user_query(models.Model):
    # user=models.ForeignKey(userclient,on_delete=models.CASCADE)
    Q_email=models.EmailField()
    query=models.CharField(max_length=200)

class adminuser(models.Model):
    name=models.CharField(max_length=20)
    is_read = models.BooleanField(default=False)
    username=models.EmailField()
    password=models.CharField(max_length=16)
    suggestion=models.TextField(null=True)
    
    def __str__(self):
        return self.username


class FakePayment(models.Model):
    user = models.ForeignKey(datadesire, on_delete=models.CASCADE, related_name="payments",null=True) 
    name = models.CharField(max_length=100)
    email = models.EmailField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_id = models.CharField(max_length=20, unique=True)
    status = models.CharField(max_length=20, choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.transaction_id}"

class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone=models.CharField(max_length=12)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class UserDocument(models.Model):
    DOCUMENT_TYPES = [
        ('Pan card', 'Pan card'),
        ('National ID', 'National ID'),
    ]
    user = models.ForeignKey(datadesire, on_delete=models.CASCADE, related_name="documents")  
    document_type = models.CharField(max_length=20, choices=DOCUMENT_TYPES)  
    document_file = models.FileField(upload_to="documents/")  
    uploaded_at = models.DateTimeField(auto_now_add=True)  

    def __str__(self):
        return f"{self.user.email} - {self.document_type}"
    
class Reservation(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone=models.CharField(max_length=12)
    company=models.CharField(max_length=100)
    venue=models.CharField(max_length=100)
    typeofevent=models.CharField(max_length=100)
    dateprimary=models.DateField()
    datesecondary=models.DateField()
    abouttheevent=models.TextField()

    def __str__(self):
        return self.name

class inquiry(models.Model):
   
    email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email
    

appeventor/forms.py
from django import forms
from .models import FakePayment,Feedback
import random, string

class FakePaymentForm(forms.ModelForm):
    class Meta:
        model = FakePayment
        fields = ['name', 'email', 'amount']
      

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.transaction_id = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))
        if commit:
            instance.save()
        return instance



class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'email', 'message']

appeventor/views.py
from django.shortcuts import render,redirect,HttpResponse
from appeventor.models import datadesire ,adminuser,user_query,Reservation
from django.conf import settings
from django.http import JsonResponse
from .forms import FakePaymentForm,FeedbackForm
from .models import FakePayment,Feedback,UserDocument

# Create your views here.
def home(request):
    if 'user_id' in request.session:
        user_id = request.session['user_id']  
        user = datadesire.objects.get(id=user_id)
        return render(request,"index.html",{'user':user})
    return render(request,"index.html")

def about(request):
    if 'user_id' in request.session:
        user_id = request.session['user_id']  
        user = datadesire.objects.get(id=user_id)
        return render(request,"about.html",{'user':user})
    return render(request,"about.html")

def rent_venue(request):
    if 'user_id' in request.session:
        user_id = request.session['user_id']  
        user = datadesire.objects.get(id=user_id)
        if request.method == "POST":
            name = request.POST['name']
            email = request.POST['email']
            phone = request.POST['phone_number']
            company = request.POST['company_organization']
            venue=request.POST['venue_requested']
            typeevent=request.POST['type_event']
            datefirst=request.POST['date-requested-first']
            datesecond=request.POST['date-requested-second']
            abouthosting=request.POST['about-event-hosting']
            print(name,email,phone,company,venue,typeevent,datefirst,datesecond,abouthosting)
            user=Reservation.objects.create(name=name,email=email,phone=phone,company=company,venue=venue,typeofevent=typeevent,dateprimary=datefirst,datesecondary=datesecond,abouttheevent=abouthosting)
            user.save()
            return redirect(rent_venue)
        return render(request,"rent-venue.html",{'user':user})
    return render(request,"rent-venue.html")

def shows_events(request):
    if 'user_id' in request.session:
        user_id = request.session['user_id']  
        user = datadesire.objects.get(id=user_id)
        return render(request,"shows-events.html",{'user':user})
    return render(request,"shows-events.html")

def corporate_party(request):
    if 'user_id' in request.session:
        user_id = request.session['user_id']  
        user = datadesire.objects.get(id=user_id)
        return render(request,"corporate_party.html",{'user':user})
    return render(request,"corporate_party.html")

def tickets(request):
    if 'user_id' in request.session:
        user_id = request.session['user_id']  
        user = datadesire.objects.get(id=user_id)
        return render(request,"tickets.html",{'user':user})
    return render(request,"tickets.html")

def ticket_details(request):
    if 'user_id' in request.session:
        user_id = request.session['user_id']  
        user = datadesire.objects.get(id=user_id)
        amount=request.GET.get("amount",00)
        event=request.GET.get("event",'None')
        location=request.GET.get("location",'None')
        return render(request,"ticket-details.html",{'user':user,'amount':amount,'event':event,'location':location})
    return render(request,"ticket-details.html")

def event_details(request):
    if 'user_id' in request.session:
        user_id = request.session['user_id']  
        user = datadesire.objects.get(id=user_id)
        return render(request,"event-details.html",{'user':user})
    return render(request,"event-details.html")

def user_login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']

        # Check if email exists in database
        user = datadesire.objects.filter(email=email, password=password).first()

        if user:
            request.session['user_id'] = user.id  # Session 
            return redirect(clienthome)  # Redirect to dashboard page
        else:
            error = "Invalid email or password"
            return render(request, "login.html", {'error': error})

    return render(request, "login.html")
def user_register(request):
    if request.method == "POST":
        name = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        # Check if email already exists
        if datadesire.objects.filter(email=email).exists():
            error = "This email is already registered. Please use a different email."
            return render(request, "register.html", {'error': error})

        # Check password match
        if password1 != password2:
            error = "Passwords do not match."
            return render(request, "register.html", {'error1': error})
        # If email is unique and passwords match, create a new user
        user = datadesire.objects.create(name=name, email=email, password=password1)
        user.save()

        return redirect(user_login)  # Ensure 'user_login' is a valid view name

    return render(request, "register.html")

def user_logout(request):
    request.session.flush()
    return redirect(user_login)

#admin side

def pages_login(request):
    if request.method == "POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        try:
            user = adminuser.objects.filter(username=username, password=password).first()
            if user:
        # Set session data
                request.session['id'] = user.id
                request.session['username'] = user.username 
                return redirect(adminhome)
            else:
                 HttpResponse("Invalid credentials.")
        except Exception as e:
            return HttpResponse(f"Error: {e}")
        
    return render(request,"admin/pages-login.html")

def adminhome(request):
    data=request.session.get('id')
    user=adminuser.objects.get(id=data)
    values=datadesire.objects.all()
    count=values.count()
    Amount=FakePayment.objects.all()
    d1=Amount.values('amount')
    am=sum([i['amount'] for i in d1])
    print(am)
    return render(request,"admin/index2.html",{'user':user,'count':count,'amount_count':am})

def client_profile(request):
    data=request.session.get('id')
    user=adminuser.objects.get(id=data)
    data=datadesire.objects.all()
    return render(request,"admin/client-profile.html",{'user':user,'show':data})


def send_suggestions(request):
    data=request.session.get('id')
    user1=adminuser.objects.get(pk=data)
    user=adminuser.objects.get(id=data)
    # adminuser.objects.filter(is_read=False).update(is_read=True)
    if request.method == "POST":
        suggestion=request.POST.get("suggestion")
        # adminuser.objects.filter(is_read=False).update(is_read=True)
        user1.suggestion=suggestion
        user1.save()      
    return render(request,"admin/send-suggestions.html",{'user':user})

def admin_profile(request):
    data=request.session.get('id')
    user=adminuser.objects.get(id=data)
    return render(request,"admin/users-profile.html",{'user':user})

def view_documents(request):
    data=request.session.get('id')
    user=adminuser.objects.get(id=data)
    return render(request,"admin/view-documents.html",{'user':user})

def view_receive_payment(request):
    data=request.session.get('id')
    user=adminuser.objects.get(id=data)
    amount=FakePayment.objects.all()
    return render(request,"admin/view-receive-payment.html",{'user':user,"amount_show":amount})

def show_reservations(request):
    reservations = Reservation.objects.all()
    return render(request, 'show_reservations.html', {'reservations': reservations})

def view_suggestions(request):
    adminuser.objects.filter(is_read=False).update(is_read=True)
    data=request.session.get('id')
    user=adminuser.objects.get(id=data)
    query=user_query.objects.all()
    print(query)
    return render(request,"admin/view-suggestions.html",{'user':user,'data':query})

def admin_log_out(request):
    request.session.flush()  
    return redirect(pages_login)
def delete(request,id):
    data=datadesire.objects.get(pk=id)
    data.delete()
    return redirect(client_profile)
def update(request,id):
    return redirect(client_profile)


#client side


def log_out(request):
    request.session.flush()  
    return redirect(user_login)


# client profile panal

def clienthome(request):
    data=request.session.get('user_id')
    user=datadesire.objects.get(id=data)
    print(user)
    return render(request,"clientpenal/index.html",{'user':user})

def payment_info(request):
    data=request.session.get('user_id')
    user=datadesire.objects.get(id=data)
    user=user.name
    amount=FakePayment.objects.filter(name=user)
    # print(amount)
    return render(request,"clientpenal/payment-info.html",{'user':user,'amount_detail':amount})

def profile(request):
    data=request.session.get('user_id')
    user=datadesire.objects.get(id=data)
    return render(request,"clientpenal/profile.html",{'user':user})

def document(request):
    data=request.session.get('user_id')
    user=datadesire.objects.get(id=data)
    if request.method == "POST":
        document_type = request.POST.get("d_id")
        document_file = request.FILES.get("document")
        try:
            user_profile = datadesire.objects.get(id=user)  
        except datadesire.DoesNotExist:
            return redirect("login")  

        
        UserDocument.objects.create(user=user_profile, document_type=document_type, document_file=document_file)
        return redirect(home) 
    return render(request,"clientpenal/send-document.html",{'user':user})
def view_suggestion(request):
    data=request.session.get('user_id')
    user=datadesire.objects.get(id=data)
    data=adminuser.objects.all()
    return render(request,"clientpenal/view_suggestion.html",{'user':user,'data':data})

def send_query(request):
    data=request.session.get('user_id')

appeventor/templates/clientpenal/send-document.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Document</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="../static/clientpenal/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="../static/clientpenal/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="../static/clientpenal/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="../static/clientpenal/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="../static/clientpenal/css/style.css" rel="stylesheet">
</head>

<body>
    <div class=" position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="{% url 'index'%}" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>Event</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="../static/clientpenal/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">{{user.name}}</h6>
                        <span>USER</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="{% url 'clienthome'%}" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                   
                    
                    <a href="{% url 'send_query'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Send Query</a>
                    <a href="{% url 'view_suggestion'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>View Suggestion</a>
                    <a href="{% url 'document'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Send Document</a>
                    <a href="{% url 'payment_info'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Payment Info</a>
                    
                    <!-- <a href="table.html" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Tables</a> -->
                    <a href="{% url 'profile'%}" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Profile</a>
                    <a href="{% url 'logout'%}" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Logout</a>


                   
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->



        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="{% url 'clienthome'%}" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="../static/clientpenal/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Anurag send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="../static/clientpenal/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Vinay send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="../static/clientpenal/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Priyesh send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all message</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="../static/clientpenal/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">{{user.name}}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            
                            <a href="#" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->


            <!-- Form Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-12">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Send Documents Form</h6>
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                            
                                <div class="mb-3">
                                    <label for="id_document_type" class="form-label">Select Document Type</label>
                                    <select class="form-control" name="document_type" required>
                                        <option selected disabled>Choose...</option>
                                        <option value="Pan card">Pan Card</option>
                                        <option value="National ID">National ID</option>
                                    </select>   
                                </div>
                            
                                <div class="mb-3">
                                    <label for="doc1" class="form-label">Upload Document</label>
                                    <input type="file" class="form-control" id="doc1" name="document_file" required>
                                </div> 
                                
                                <button type="submit" class="btn btn-primary w-100">Upload</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Form End -->


            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Kushal-Singwani@dreamseventmanagement</a>, All Right Reserved. 
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="https://htmlcodex.com">Kushal-Singwani</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../static/clientpenal/lib/chart/chart.min.js"></script>
    <script src="../static/clientpenal/lib/easing/easing.min.js"></script>
    <script src="../static/clientpenal/lib/waypoints/waypoints.min.js"></script>
    <script src="../static/clientpenal/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="../static/clientpenal/lib/tempusdominus/js/moment.min.js"></script>
    <script src="../static/clientpenal/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="../static/clientpenal/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="../static/clientpenal/js/main.js"></script>
</body>

</html>